In [1]:
import tensorflow as tf
import numpy as np

# Basics for GCN

This notebook provides some intuition for some basic math operations, variables and their meaning in GCN.

## Adjacency matrix A

A is a N * N matrix, N being the number of nodes in the graph. a_ij = x meaning that there is a connection between nodes i and j with weight x. A can be symmetric (undirected graph), but it doesn't have to be (directed graph). Values can be binary (unweighted) or non-binary (weighted). 

In [2]:
A = np.matrix([[0,1,0,1], [1,0,1,1], [0,1,0,0], [1,1,0,1]])
print(A)

[[0 1 0 1]
 [1 0 1 1]
 [0 1 0 0]
 [1 1 0 1]]


## Degree of a node and Degree Matrix D

The degree of a Node n shows how many direct neighbors a node has. D is a matrix that has the respective degree of each node on the diagonal.

In [3]:
def to_diagonal(arr):
    d = np.zeros([arr.shape[0],arr.shape[0]])
    np.fill_diagonal(d, arr)
    return d

def calc_degree_matrix(mat):
    node_degrees = mat.sum(axis=1)
    return to_diagonal(node_degrees)

D = calc_degree_matrix(A)
print(D)

[[2. 0. 0. 0.]
 [0. 3. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 3.]]


## Laplacian L

The graph laplacian is defined as L = D - A

In [4]:
def create_graph_lapl(mat):
    return calc_degree_matrix(mat) - mat

L = create_graph_lapl(A)
print(L)

[[ 2. -1.  0. -1.]
 [-1.  3. -1. -1.]
 [ 0. -1.  1.  0.]
 [-1. -1.  0.  2.]]


## Normalized Laplacian L_norm

The Laplacian needs to be normed. This helps gradient-based operations to perform better.

In [5]:
def calc_degree_matrix_norm(mat):
    return to_diagonal(np.power(mat.sum(axis=1), -0.5))

def create_graph_lapl_norm(a):
    size = a.shape[-1]
    D_norm = calc_degree_matrix_norm(a)
    L_norm = np.ones(size) - (D_norm @ a @ D_norm )
    return L_norm

In [6]:
A = np.matrix([[0., 0., 1., 1., 1.],
          [1., 0., 1., 0., 1.],
          [1., 0., 0., 0., 1.],
          [0., 1., 0., 0., 0.],
          [0., 0., 1., 1., 0.]])

L_norm = create_graph_lapl_norm(A)
print(L_norm)

[[1.         1.         0.59175171 0.42264973 0.59175171]
 [0.66666667 1.         0.59175171 1.         0.59175171]
 [0.59175171 1.         1.         1.         0.5       ]
 [1.         0.42264973 1.         1.         1.        ]
 [1.         1.         0.5        0.29289322 1.        ]]
